version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: unsplash_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: unsplash_clone
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d unsplash_clone"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
